export const INSERT = 'ara/posts/INSERT'
export const SAVE = 'ara/posts/SAVE'
export const REMOVE = 'ara/posts/REMOVE'
export const UPDATE = 'ara/posts/UPDATE'
export const INIT_PERSISTED_POSTS_STATE = 'ara/posts/INIT_PERSISTED_POSTS_STATE'
